### PR TITLE
Enhanced MPI functionality from JCSDA

### PR DESCRIPTION
**Pull request by mmiesch**
We at JCSDA added new fortran interfaces to some of the eckit mpi routines such as mpi_allgather.  And, we added other functionality to existing interfaces, such as broadcasting logical arrays.

### CODE REVIEW

**Comment by wdeconinck** [comment]
Dear @mmiesch , this looks wonderful. Thanks! There's just one more thing, which is the CLA that needs to be checked, before I can merge this in. Don't worry about conflicts that must be resolved. I'll take care of that.

**Comment by mmiesch** [comment]
Hi @wdeconinck - Thanks for your attention to this - I have signed the CLA, although the GitHub thread still lists it as pending.  Please let me know if this is sufficient.  Happy New Year!

**Comment by wdeconinck** [comment]
@mmiesch, it may be that @danholdaway also needs to sign it as a contributor. We're still experimenting with the CLA-assistant. Sorry for the inconvenience.

**Comment by mmiesch** [comment]
Thanks @wdeconinck - I will ask Dan.  However, as a NASA employee, he might be unable to work because of the continuing US government shut-down.  I will keep you posted.

**Pull request merged**
